
import java.math.BigInteger;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PrivateKey;
import java.security.Signature;
import java.util.Scanner;

public class DSANew {
	public static String getMd5(String input) {
		try {
			MessageDigest md = MessageDigest.getInstance("MD5");
			byte[] messageDigest = md.digest(input.getBytes());

			BigInteger no = new BigInteger(1, messageDigest);

			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		} catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	public static void main(String args[]) throws Exception {
		Scanner sc = new Scanner(System.in);

		try {
			KeyPairGenerator keyPairGen = KeyPairGenerator.getInstance("DSA");
			keyPairGen.initialize(2048);
			KeyPair pair = keyPairGen.generateKeyPair();
			PrivateKey privKey = pair.getPrivate();
			Signature sign = Signature.getInstance("SHA256withDSA");

			sign.initSign(privKey);

			System.out.print("Create the Digital Signature: ");
			String value1 = getMd5(sc.nextLine());
			System.out.println("Your HashCode Generated by MD5 is: " + value1);

			byte[] val1byte = value1.getBytes();

			System.out.println("Signature Value 1: " + val1byte);
			System.out.print("\n");

			sign.update(val1byte);
			byte[] signature = sign.sign();

			System.out.print("Enter to Verify: ");
			String value2 = getMd5(sc.nextLine());
			System.out.println("Your HashCode Generated by MD5 is: " + value2);

			byte[] val2byte = value2.getBytes();

			System.out.println("Signature Value 2: " + val2byte);
			System.out.print("\n");

			sign.initVerify(pair.getPublic());
			sign.update(val2byte);

			if (value1.equals(value2) == true) {
				System.out.println("Hash Value Match");
				boolean bool = sign.verify(signature);
				if (bool) {
					System.out.println("Signature Verified");
				} else {
					System.out.println("Signature Failed");
				}
			} else {
				System.out.println("Hash Value Not Match");
			}
		} catch (Exception e) {
			System.out.println("Digital Signature Error!");
		}
	}
}